# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "im_onix"
  s.version = "0.9.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["julbouln"]
  s.date = "2013-11-29"
  s.description = "immat\u{e9}riel.fr onix parser"
  s.email = "jboulnois@immateriel.fr"
  s.executables = ["onix3_to_onix2.rb", "onix3_to_onix3.rb", "onix_pp.rb"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "bin/onix3_to_onix2.rb",
    "bin/onix3_to_onix3.rb",
    "bin/onix_pp.rb",
    "data/codelists/onix-codelist-1.htm",
    "data/codelists/onix-codelist-10.htm",
    "data/codelists/onix-codelist-100.htm",
    "data/codelists/onix-codelist-101.htm",
    "data/codelists/onix-codelist-102.htm",
    "data/codelists/onix-codelist-11.htm",
    "data/codelists/onix-codelist-12.htm",
    "data/codelists/onix-codelist-121.htm",
    "data/codelists/onix-codelist-13.htm",
    "data/codelists/onix-codelist-138.htm",
    "data/codelists/onix-codelist-139.htm",
    "data/codelists/onix-codelist-14.htm",
    "data/codelists/onix-codelist-140.htm",
    "data/codelists/onix-codelist-141.htm",
    "data/codelists/onix-codelist-142.htm",
    "data/codelists/onix-codelist-143.htm",
    "data/codelists/onix-codelist-144.htm",
    "data/codelists/onix-codelist-145.htm",
    "data/codelists/onix-codelist-146.htm",
    "data/codelists/onix-codelist-147.htm",
    "data/codelists/onix-codelist-148.htm",
    "data/codelists/onix-codelist-149.htm",
    "data/codelists/onix-codelist-15.htm",
    "data/codelists/onix-codelist-150.htm",
    "data/codelists/onix-codelist-151.htm",
    "data/codelists/onix-codelist-152.htm",
    "data/codelists/onix-codelist-153.htm",
    "data/codelists/onix-codelist-154.htm",
    "data/codelists/onix-codelist-155.htm",
    "data/codelists/onix-codelist-156.htm",
    "data/codelists/onix-codelist-157.htm",
    "data/codelists/onix-codelist-158.htm",
    "data/codelists/onix-codelist-159.htm",
    "data/codelists/onix-codelist-16.htm",
    "data/codelists/onix-codelist-160.htm",
    "data/codelists/onix-codelist-161.htm",
    "data/codelists/onix-codelist-162.htm",
    "data/codelists/onix-codelist-163.htm",
    "data/codelists/onix-codelist-164.htm",
    "data/codelists/onix-codelist-165.htm",
    "data/codelists/onix-codelist-166.htm",
    "data/codelists/onix-codelist-167.htm",
    "data/codelists/onix-codelist-168.htm",
    "data/codelists/onix-codelist-169.htm",
    "data/codelists/onix-codelist-17.htm",
    "data/codelists/onix-codelist-170.htm",
    "data/codelists/onix-codelist-171.htm",
    "data/codelists/onix-codelist-172.htm",
    "data/codelists/onix-codelist-173.htm",
    "data/codelists/onix-codelist-174.htm",
    "data/codelists/onix-codelist-175.htm",
    "data/codelists/onix-codelist-176.htm",
    "data/codelists/onix-codelist-177.htm",
    "data/codelists/onix-codelist-178.htm",
    "data/codelists/onix-codelist-179.htm",
    "data/codelists/onix-codelist-18.htm",
    "data/codelists/onix-codelist-184.htm",
    "data/codelists/onix-codelist-19.htm",
    "data/codelists/onix-codelist-196.htm",
    "data/codelists/onix-codelist-197.htm",
    "data/codelists/onix-codelist-198.htm",
    "data/codelists/onix-codelist-2.htm",
    "data/codelists/onix-codelist-20.htm",
    "data/codelists/onix-codelist-203.htm",
    "data/codelists/onix-codelist-204.htm",
    "data/codelists/onix-codelist-21.htm",
    "data/codelists/onix-codelist-22.htm",
    "data/codelists/onix-codelist-23.htm",
    "data/codelists/onix-codelist-24.htm",
    "data/codelists/onix-codelist-25.htm",
    "data/codelists/onix-codelist-26.htm",
    "data/codelists/onix-codelist-27.htm",
    "data/codelists/onix-codelist-28.htm",
    "data/codelists/onix-codelist-29.htm",
    "data/codelists/onix-codelist-3.htm",
    "data/codelists/onix-codelist-30.htm",
    "data/codelists/onix-codelist-31.htm",
    "data/codelists/onix-codelist-32.htm",
    "data/codelists/onix-codelist-33.htm",
    "data/codelists/onix-codelist-34.htm",
    "data/codelists/onix-codelist-35.htm",
    "data/codelists/onix-codelist-36.htm",
    "data/codelists/onix-codelist-37.htm",
    "data/codelists/onix-codelist-38.htm",
    "data/codelists/onix-codelist-39.htm",
    "data/codelists/onix-codelist-40.htm",
    "data/codelists/onix-codelist-41.htm",
    "data/codelists/onix-codelist-42.htm",
    "data/codelists/onix-codelist-43.htm",
    "data/codelists/onix-codelist-44.htm",
    "data/codelists/onix-codelist-45.htm",
    "data/codelists/onix-codelist-46.htm",
    "data/codelists/onix-codelist-47.htm",
    "data/codelists/onix-codelist-48.htm",
    "data/codelists/onix-codelist-49.htm",
    "data/codelists/onix-codelist-5.htm",
    "data/codelists/onix-codelist-50.htm",
    "data/codelists/onix-codelist-51.htm",
    "data/codelists/onix-codelist-52.htm",
    "data/codelists/onix-codelist-53.htm",
    "data/codelists/onix-codelist-54.htm",
    "data/codelists/onix-codelist-55.htm",
    "data/codelists/onix-codelist-56.htm",
    "data/codelists/onix-codelist-57.htm",
    "data/codelists/onix-codelist-58.htm",
    "data/codelists/onix-codelist-59.htm",
    "data/codelists/onix-codelist-6.htm",
    "data/codelists/onix-codelist-60.htm",
    "data/codelists/onix-codelist-61.htm",
    "data/codelists/onix-codelist-62.htm",
    "data/codelists/onix-codelist-63.htm",
    "data/codelists/onix-codelist-64.htm",
    "data/codelists/onix-codelist-65.htm",
    "data/codelists/onix-codelist-66.htm",
    "data/codelists/onix-codelist-67.htm",
    "data/codelists/onix-codelist-68.htm",
    "data/codelists/onix-codelist-69.htm",
    "data/codelists/onix-codelist-7.htm",
    "data/codelists/onix-codelist-70.htm",
    "data/codelists/onix-codelist-71.htm",
    "data/codelists/onix-codelist-72.htm",
    "data/codelists/onix-codelist-73.htm",
    "data/codelists/onix-codelist-74.htm",
    "data/codelists/onix-codelist-75.htm",
    "data/codelists/onix-codelist-76.htm",
    "data/codelists/onix-codelist-77.htm",
    "data/codelists/onix-codelist-78.htm",
    "data/codelists/onix-codelist-79.htm",
    "data/codelists/onix-codelist-8.htm",
    "data/codelists/onix-codelist-80.htm",
    "data/codelists/onix-codelist-81.htm",
    "data/codelists/onix-codelist-82.htm",
    "data/codelists/onix-codelist-83.htm",
    "data/codelists/onix-codelist-84.htm",
    "data/codelists/onix-codelist-85.htm",
    "data/codelists/onix-codelist-86.htm",
    "data/codelists/onix-codelist-87.htm",
    "data/codelists/onix-codelist-88.htm",
    "data/codelists/onix-codelist-89.htm",
    "data/codelists/onix-codelist-9.htm",
    "data/codelists/onix-codelist-90.htm",
    "data/codelists/onix-codelist-91.htm",
    "data/codelists/onix-codelist-92.htm",
    "data/codelists/onix-codelist-93.htm",
    "data/codelists/onix-codelist-94.htm",
    "data/codelists/onix-codelist-95.htm",
    "data/codelists/onix-codelist-96.htm",
    "data/codelists/onix-codelist-97.htm",
    "data/codelists/onix-codelist-98.htm",
    "data/codelists/onix-codelist-99.htm",
    "lib/im_onix.rb",
    "lib/onix/code.rb",
    "lib/onix/collateral_detail.rb",
    "lib/onix/contributor.rb",
    "lib/onix/descriptive_detail.rb",
    "lib/onix/entity.rb",
    "lib/onix/error.rb",
    "lib/onix/helper.rb",
    "lib/onix/identifier.rb",
    "lib/onix/onix_date.rb",
    "lib/onix/onix_message.rb",
    "lib/onix/price.rb",
    "lib/onix/product.rb",
    "lib/onix/product_supply.rb",
    "lib/onix/publishing_detail.rb",
    "lib/onix/related_material.rb",
    "lib/onix/subject.rb",
    "lib/onix/subset.rb",
    "lib/onix/supporting_resource.rb",
    "lib/onix/territory.rb"
  ]
  s.homepage = "http://github.com/immateriel/im_onix"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "immat\u{e9}riel.fr onix parser"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

