# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "im_onix"
  s.version = "0.9.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["julbouln"]
  s.date = "2015-03-26"
  s.description = "immat\u{e9}riel.fr onix parser"
  s.email = "jboulnois@immateriel.fr"
  s.executables = ["html_codelist_to_yml.rb", "onix3_to_onix2.rb", "onix3_to_onix3.rb", "onix_pp.rb", "onix_split.rb"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "bin/html_codelist_to_yml.rb",
    "bin/onix3_to_onix2.rb",
    "bin/onix3_to_onix3.rb",
    "bin/onix_pp.rb",
    "bin/onix_split.rb",
    "data/codelists/codelist-1.yml",
    "data/codelists/codelist-10.yml",
    "data/codelists/codelist-100.yml",
    "data/codelists/codelist-101.yml",
    "data/codelists/codelist-102.yml",
    "data/codelists/codelist-11.yml",
    "data/codelists/codelist-12.yml",
    "data/codelists/codelist-121.yml",
    "data/codelists/codelist-13.yml",
    "data/codelists/codelist-138.yml",
    "data/codelists/codelist-139.yml",
    "data/codelists/codelist-14.yml",
    "data/codelists/codelist-140.yml",
    "data/codelists/codelist-141.yml",
    "data/codelists/codelist-142.yml",
    "data/codelists/codelist-143.yml",
    "data/codelists/codelist-144.yml",
    "data/codelists/codelist-145.yml",
    "data/codelists/codelist-146.yml",
    "data/codelists/codelist-147.yml",
    "data/codelists/codelist-148.yml",
    "data/codelists/codelist-149.yml",
    "data/codelists/codelist-15.yml",
    "data/codelists/codelist-150.yml",
    "data/codelists/codelist-151.yml",
    "data/codelists/codelist-152.yml",
    "data/codelists/codelist-153.yml",
    "data/codelists/codelist-154.yml",
    "data/codelists/codelist-155.yml",
    "data/codelists/codelist-156.yml",
    "data/codelists/codelist-157.yml",
    "data/codelists/codelist-158.yml",
    "data/codelists/codelist-159.yml",
    "data/codelists/codelist-16.yml",
    "data/codelists/codelist-160.yml",
    "data/codelists/codelist-161.yml",
    "data/codelists/codelist-162.yml",
    "data/codelists/codelist-163.yml",
    "data/codelists/codelist-164.yml",
    "data/codelists/codelist-165.yml",
    "data/codelists/codelist-166.yml",
    "data/codelists/codelist-167.yml",
    "data/codelists/codelist-168.yml",
    "data/codelists/codelist-169.yml",
    "data/codelists/codelist-17.yml",
    "data/codelists/codelist-170.yml",
    "data/codelists/codelist-171.yml",
    "data/codelists/codelist-172.yml",
    "data/codelists/codelist-173.yml",
    "data/codelists/codelist-174.yml",
    "data/codelists/codelist-175.yml",
    "data/codelists/codelist-176.yml",
    "data/codelists/codelist-177.yml",
    "data/codelists/codelist-178.yml",
    "data/codelists/codelist-179.yml",
    "data/codelists/codelist-18.yml",
    "data/codelists/codelist-184.yml",
    "data/codelists/codelist-19.yml",
    "data/codelists/codelist-196.yml",
    "data/codelists/codelist-197.yml",
    "data/codelists/codelist-198.yml",
    "data/codelists/codelist-2.yml",
    "data/codelists/codelist-20.yml",
    "data/codelists/codelist-203.yml",
    "data/codelists/codelist-204.yml",
    "data/codelists/codelist-21.yml",
    "data/codelists/codelist-22.yml",
    "data/codelists/codelist-23.yml",
    "data/codelists/codelist-24.yml",
    "data/codelists/codelist-25.yml",
    "data/codelists/codelist-26.yml",
    "data/codelists/codelist-27.yml",
    "data/codelists/codelist-28.yml",
    "data/codelists/codelist-29.yml",
    "data/codelists/codelist-3.yml",
    "data/codelists/codelist-30.yml",
    "data/codelists/codelist-31.yml",
    "data/codelists/codelist-32.yml",
    "data/codelists/codelist-33.yml",
    "data/codelists/codelist-34.yml",
    "data/codelists/codelist-35.yml",
    "data/codelists/codelist-36.yml",
    "data/codelists/codelist-37.yml",
    "data/codelists/codelist-38.yml",
    "data/codelists/codelist-39.yml",
    "data/codelists/codelist-40.yml",
    "data/codelists/codelist-41.yml",
    "data/codelists/codelist-42.yml",
    "data/codelists/codelist-43.yml",
    "data/codelists/codelist-44.yml",
    "data/codelists/codelist-45.yml",
    "data/codelists/codelist-46.yml",
    "data/codelists/codelist-47.yml",
    "data/codelists/codelist-48.yml",
    "data/codelists/codelist-49.yml",
    "data/codelists/codelist-5.yml",
    "data/codelists/codelist-50.yml",
    "data/codelists/codelist-51.yml",
    "data/codelists/codelist-52.yml",
    "data/codelists/codelist-53.yml",
    "data/codelists/codelist-54.yml",
    "data/codelists/codelist-55.yml",
    "data/codelists/codelist-56.yml",
    "data/codelists/codelist-57.yml",
    "data/codelists/codelist-58.yml",
    "data/codelists/codelist-59.yml",
    "data/codelists/codelist-6.yml",
    "data/codelists/codelist-60.yml",
    "data/codelists/codelist-61.yml",
    "data/codelists/codelist-62.yml",
    "data/codelists/codelist-63.yml",
    "data/codelists/codelist-64.yml",
    "data/codelists/codelist-65.yml",
    "data/codelists/codelist-66.yml",
    "data/codelists/codelist-67.yml",
    "data/codelists/codelist-68.yml",
    "data/codelists/codelist-69.yml",
    "data/codelists/codelist-7.yml",
    "data/codelists/codelist-70.yml",
    "data/codelists/codelist-71.yml",
    "data/codelists/codelist-72.yml",
    "data/codelists/codelist-73.yml",
    "data/codelists/codelist-74.yml",
    "data/codelists/codelist-75.yml",
    "data/codelists/codelist-76.yml",
    "data/codelists/codelist-77.yml",
    "data/codelists/codelist-78.yml",
    "data/codelists/codelist-79.yml",
    "data/codelists/codelist-8.yml",
    "data/codelists/codelist-80.yml",
    "data/codelists/codelist-81.yml",
    "data/codelists/codelist-82.yml",
    "data/codelists/codelist-83.yml",
    "data/codelists/codelist-84.yml",
    "data/codelists/codelist-85.yml",
    "data/codelists/codelist-86.yml",
    "data/codelists/codelist-87.yml",
    "data/codelists/codelist-88.yml",
    "data/codelists/codelist-89.yml",
    "data/codelists/codelist-9.yml",
    "data/codelists/codelist-90.yml",
    "data/codelists/codelist-91.yml",
    "data/codelists/codelist-92.yml",
    "data/codelists/codelist-93.yml",
    "data/codelists/codelist-94.yml",
    "data/codelists/codelist-95.yml",
    "data/codelists/codelist-96.yml",
    "data/codelists/codelist-97.yml",
    "data/codelists/codelist-98.yml",
    "data/codelists/codelist-99.yml",
    "lib/im_onix.rb",
    "lib/onix/code.rb",
    "lib/onix/collateral_detail.rb",
    "lib/onix/contributor.rb",
    "lib/onix/descriptive_detail.rb",
    "lib/onix/entity.rb",
    "lib/onix/error.rb",
    "lib/onix/helper.rb",
    "lib/onix/identifier.rb",
    "lib/onix/onix_date.rb",
    "lib/onix/onix_message.rb",
    "lib/onix/price.rb",
    "lib/onix/product.rb",
    "lib/onix/product_supply.rb",
    "lib/onix/publishing_detail.rb",
    "lib/onix/related_material.rb",
    "lib/onix/subject.rb",
    "lib/onix/subset.rb",
    "lib/onix/supporting_resource.rb",
    "lib/onix/territory.rb"
  ]
  s.homepage = "http://github.com/immateriel/im_onix"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "immat\u{e9}riel.fr onix parser"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

